### ISSUE TITLE
Lab 9 broken - New Sonarqube image requires authentication

### ISSUE THREAD

**Issue by gbengataylor** [RedHatGov/devsecops-workshop-dashboard#24]
After adding the code analysis step, mvn plugin command fails. When sonarqube is installed, a password is generated and stored in a secret. A workaround is to turn off authentication

![image](https://user-images.githubusercontent.com/30447678/115161767-81883980-a06d-11eb-8abd-2223d66b3c73.png)

A better fix would be to update the sonarqube settings during install and update the configuration

```
- name: Update sonarqube settings
    shell: >-
      devsecops-api sonarqube update-setting
      {{ sonarqube_url }}
      --login-username admin --login-password admin
      --new-login-password test123
      --setting-name 'sonar.forceAuthentication'
      --setting-value 'true'
    register: sonarqube_settings
    failed_when: sonarqube_settings.rc != 0
    until: not sonarqube_settings.failed
    retries: 3
    delay: 10
```

**Comment by andykrohg** [comment]
Addressing this here: https://github.com/RedHatGov/devsecops-operator/pull/13
